# This is a TOML document.

title = "TOML Configure"

[study]
weekday = ['', "ПОНЕДЕЛЬНИК", "ВТОРНИК", "СРЕДА", "ЧЕТВЕРГ", "ПЯТНИЦА", "СУББОТА", "ВОСКРЕСЕНЬЕ"]
select_day = ['today', 'tomorrow', 'after_tom', 'to_2_day']
tasks = ['S0', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'K1', 'K2', 'K3', 'K4', 'K5', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6']

[metodic]
static = 'https://drive.google.com/file/d/172EuTxLjZlYR0GYi03wdbzu70kae4RdC/view?usp=sharing'
kinematic = 'https://drive.google.com/file/d/1i23gh8Kcsu-R5OkyHfdbp7SFUW2c73kx/view?usp=sharing'
dynamic = 'https://drive.google.com/file/d/1wrluEFNR18gYT1wFe-oLsmar9pxSB8ZH/view?usp=sharing'

[books]
shortcourse = 'https://drive.google.com/file/d/17OhsVDAaPVkdBEMbjl3wR0Scj7WjeMYo/view?usp=drive_link'

[contact]
vk = 'https://vk.com/general_soldatov'
telegram = 'https://t.me/general_soldatov'

[mailer]
profile = ['Все', 'НТТС', 'Агроинженерия']
group = ['1-а', '1-б', '8-а', '8-б', '9-а']